default_language_version:
    python: python3

repos:
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: ['--exclude','SC1090,SC2046,SC2005,SC2035,SC2086']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-ast
      name: check-ast
      description: Simply check whether files parse as valid python.
    - id: check-builtin-literals
      name: check-builtin-literals
      description: Require literal syntax when initializing empty, or zero Python builtin types.
    - id: check-docstring-first
      name: check-docstring-first
      description: Checks for a common error of placing code before the docstring.
    - id: check-added-large-files
      name: check-added-large-files
      description: Prevent giant files from being committed.
    - id: check-merge-conflict
      name: check-merge-conflict
      description: Check for files that contain merge conflict strings.
    - id: check-symlinks
      name: check-symlinks
      description: Checks for symlinks which do not point to anything.
    - id: check-yaml
      name: check-yaml
      description: Attempts to load all yaml files to verify syntax.
    - id: check-toml
      name: check-toml
      description: Attempts to load all TOML files to verify syntax.
    - id: debug-statements
      name: debug-statements
      description: Check for debugger imports and py37+ breakpoint() calls in python source.
    - id: detect-private-key
      name: detect-private-key
      description: Checks for the existence of private keys.
    - id: end-of-file-fixer
      name: end-of-file-fixer
      description: Makes sure files end in a newline and only a newline.
    - id: trailing-whitespace
      name: trailing-whitespace
      description: Trims trailing whitespace
    - id: requirements-txt-fixer
      name: requirements-txt-fixer
      description: Sorts entries in requirements.txt

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --line-length=170]
